Feat/project mobile view
ImbueNetwork/imbue-frontend pull request #59
Opened 2023-04-29 13:18 UTC by vadik0101

2023-04-29 15:45 UTC, cuteolaf requested changes

2023-04-29 15:45 UTC, cuteolaf commented on src/pages/projects/[id].tsx
I see a lot of hard coded constants here and there.
`max-width-750px`
`!px-[40px] `
`mt-25px`
...

Could you please update this file to replace such constants with existing tailwind css classnames?

2023-05-01 08:25 UTC, vadik0101 commented on src/pages/projects/[id].tsx
i defined them in the tailwind config
they are not hard coded

2023-05-01 09:19 UTC, samelamin approved these changes

2023-05-01 09:19 UTC, merged